sudo: required

language: php

# Stage order
stages:
  - pre-conditions
  - test
  - quality


################
#  Test stage  #
################

php:
  - 7.4

env:
  - COMMAND="composer install"
  - COMMAND="composer update"

before_script:
  - ${COMMAND}

script:
  - php vendor/bin/phpunit --no-coverage

jobs:
  fast_finish: true

  include:

    ##########################
    #  Pre-conditions stage  #
    ##########################

    - stage: pre-conditions
      php: 7.4
      env: Syntax check PHP
      before_script:
        - composer install
      script:
        - vendor/bin/check-syntax-php.sh

    - stage: pre-conditions
      php: 7.4
      env: Syntax check YAML / XML / JSON
      before_script:
        - composer update
      script:
        - vendor/bin/check-syntax-yaml.sh
        - vendor/bin/check-syntax-xml.sh
        - vendor/bin/check-syntax-json.sh


    ###################
    #  Quality stage  #
    ###################

    - stage: quality
      php: 7.4
      env: Security check (composer install)
      before_script:
        - composer install
      script:
        - vendor/bin/security-checker security:check

    - stage: quality
      php: 7.4
      env: Security check (composer update)
      before_script:
        - composer update
      script:
        - vendor/bin/security-checker security:check

    - stage: quality
      php: 7.4
      env: Codecov
      before_script:
        - composer update
        - php vendor/bin/phpunit
      script:
        - bash <(curl -s https://codecov.io/bash)

    - stage: quality
      php: 7.4
      env: Psalm
      before_script:
        - composer update
      script:
        - vendor/bin/psalm
        - vendor/bin/psalter --issues=UnnecessaryVarAnnotation --dry-run

    - stage: quality
      php: 7.4
      env: PHP Codesniffer
      before_script:
        - composer update
      script:
        - vendor/bin/phpcs
